In [22]:
## MULTIVARIATE REGRESSION 

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [23]:
df = pd.read_csv(r"c:\Users\lenovo\Desktop\DB_progm\dataBase practise\sales_data_usa_practice.csv")
df.head()

Order ID  Order Date Customer Name Product Name     Category   Region State  \
0  ORD0001  2023-05-04    Customer 1       Laptop  Electronics  Midwest    OH   
1  ORD0002  2023-11-03    Customer 2         Desk    Furniture  Midwest    OH   
2  ORD0003  2023-10-05    Customer 3        Jeans     Clothing     West    WA   
3  ORD0004  2023-11-01    Customer 4        Jeans     Clothing    South    FL   
4  ORD0005  2024-06-01    Customer 5       Tablet  Electronics    South    GA   

   Sales Amount  Quantity Sold   Profit  
0       5705.19              4   928.19  
1      19147.89             10  4757.51  
2       4169.03              5  1217.80  
3      15806.59              9  4056.88  
4      18724.71             10  4741.58

In [24]:
import math
median_quantity = math.floor(df['Quantity Sold'].median())
median_quantity

5

In [25]:
# creating a linear regression model object
reg = linear_model.LinearRegression()
reg.fit(df[['Sales Amount', 'Quantity Sold']],df.Profit)

LinearRegression()

In [26]:
reg.coef_

array([ 0.21413936, -9.23273754])

In [27]:
reg.intercept_

np.float64(-9.149531733292406)

In [28]:
# prediction
reg.predict([[15000,7]])

c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([3138.31174361])

In [29]:
# y = m1 * x1 + m2 * x2 + b       (mannual calculation for prediction)
0.21413936 * 15000 + -9.23273754 * 7 -9.149531733292406

3138.3117054867075

In [30]:
reg.predict([[7000, 5]])

c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([1443.66231835])

In [31]:
# practice dataset 2

d = pd.read_csv(r"c:\Users\lenovo\Desktop\DB_progm\dataBase practise\salary table.csv")
d.head()

experience  test_score(/10)  interview_score(/10)  age  salary
0       five                7                   8.0   27   67000
1        two                9                   7.0   23   48000
2        ten                8                   NaN   33   54000
3      three               10                   9.0   24   57000
4        NaN                8                   NaN   21   35000

In [33]:
import math 
median_interview_score = math.floor(d['interview_score(/10)'].median())  #finding the median values to fill the null values
d['interview_score(/10)'] = d['interview_score(/10)'].fillna(median_interview_score)  # updating the sorce table
d.head()

experience  test_score(/10)  interview_score(/10)  age  salary
0       five                7                   8.0   27   67000
1        two                9                   7.0   23   48000
2        ten                8                   8.0   33   54000
3      three               10                   9.0   24   57000
4        NaN                8                   8.0   21   35000

In [34]:
# linear regression model object

reg.fit(d[['test_score(/10)', 'interview_score(/10)', 'age']],d.salary)

LinearRegression()

In [ ]:
reg.coef_     # m1, m2, m3

array([  397.82988087, -2814.62933455,  2252.59883147])

In [ ]:
reg.intercept_  # +b

np.float64(15420.51748994609)

In [37]:
reg.predict([[7,8,21]])

c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([42992.86744063])

In [38]:
reg.predict([[9,9,22]])

c:\Users\lenovo\AppData\Local\Programs\Python\Python313\Lib\site-packages\sklearn\utils\validation.py:2749: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([43226.49669929])